# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opentelemetry1 < Formula
  desc "A sample open telemetry instrumented application"
  homepage "https://github.com/prabhatsharma/opentelemetry1"
  version "0.4.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/prabhatsharma/open-telemetry1/releases/download/v0.4.1/opentelemetry1_0.4.1_Darwin_x86_64.tar.gz"
      sha256 "b93ff3d81a68414099de2747a46e3c1d2cbc30ec0f3c752fc86d4290330bd768"

      def install
        bin.install "opentelemetry1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/prabhatsharma/open-telemetry1/releases/download/v0.4.1/opentelemetry1_0.4.1_Darwin_arm64.tar.gz"
      sha256 "8027b2c505a26c91ffc9c820ff6a6cd195314bd55fb89420d9ed9aafb603a751"

      def install
        bin.install "opentelemetry1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/prabhatsharma/open-telemetry1/releases/download/v0.4.1/opentelemetry1_0.4.1_Linux_armv6.tar.gz"
      sha256 "c75011e9ccf98af6e0cb3ebb970341469c95549ccef5425d6b202064a99ed1ea"

      def install
        bin.install "opentelemetry1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/prabhatsharma/open-telemetry1/releases/download/v0.4.1/opentelemetry1_0.4.1_Linux_x86_64.tar.gz"
      sha256 "c5cc8f642a2a6b7438ec17accab1a1264a6ee37746cc6577091fb6f9f7f5dd2f"

      def install
        bin.install "opentelemetry1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prabhatsharma/open-telemetry1/releases/download/v0.4.1/opentelemetry1_0.4.1_Linux_arm64.tar.gz"
      sha256 "b822323ae8fb64d03bbd54dfb7de9e94d23c8512152ce7c3c50a50d67725f0b7"

      def install
        bin.install "opentelemetry1"
      end
    end
  end
end
