# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfGoreleaserEcr < Formula
  desc "tf-goreleaser-ecr is a sample CI/CD pipeline using Terraform and goreleaser
"
  homepage "https://github.com/prabhatsharma/tf-goreleaser-ecr"
  version "0.0.19"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/prabhatsharma/tf-goreleaser-ecr/releases/download/v0.0.19/tf-goreleaser-ecr_0.0.19_Darwin_arm64.tar.gz"
      sha256 "6ff80c1c788447b3e6f0d52bd323bea3dae69bdc3e09cdc503e1f0895bdeb559"

      def install
        bin.install "tf-goreleaser-ecr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/prabhatsharma/tf-goreleaser-ecr/releases/download/v0.0.19/tf-goreleaser-ecr_0.0.19_Darwin_x86_64.tar.gz"
      sha256 "20c45b97776cb79ccc336ce36e43131c5619259a99bd8e0c364cf38adc8986e7"

      def install
        bin.install "tf-goreleaser-ecr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/prabhatsharma/tf-goreleaser-ecr/releases/download/v0.0.19/tf-goreleaser-ecr_0.0.19_Linux_armv6.tar.gz"
      sha256 "0a2865d3843d37dbab956bc5f10b15f99e20cdeea7d196a9a8ed015a99bc915a"

      def install
        bin.install "tf-goreleaser-ecr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/prabhatsharma/tf-goreleaser-ecr/releases/download/v0.0.19/tf-goreleaser-ecr_0.0.19_Linux_x86_64.tar.gz"
      sha256 "5dfcbe2d2283f627087199724b050f1ef4129c5eec65e6d0cbec5597f7ee9d4f"

      def install
        bin.install "tf-goreleaser-ecr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prabhatsharma/tf-goreleaser-ecr/releases/download/v0.0.19/tf-goreleaser-ecr_0.0.19_Linux_arm64.tar.gz"
      sha256 "d5769a582bbb8b623f0fe719170e6b8c1039e8df6517b45ee06cb5daf1c0f9b8"

      def install
        bin.install "tf-goreleaser-ecr"
      end
    end
  end
end
