# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zinc < Formula
  desc "Zinc Search engine. A lightweight alternative to elasticsearch that requires minimal resources, written in Go."
  homepage "https://github.com/prabhatsharma/zinc"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/prabhatsharma/open-telemetry1/releases/download/v0.1.0/opentelemetry1_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "1376d100068bd69e311e045ff81723d7794412f426559068adb2050ce509a6ac"

      def install
        bin.install "opentelemetry1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/prabhatsharma/open-telemetry1/releases/download/v0.1.0/opentelemetry1_0.1.0_Darwin_arm64.tar.gz"
      sha256 "d7709b8f3cd54172d0f408ddd3bc453c7385d836cc14a625e44d8530672ccc6f"

      def install
        bin.install "opentelemetry1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/prabhatsharma/open-telemetry1/releases/download/v0.1.0/opentelemetry1_0.1.0_Linux_armv6.tar.gz"
      sha256 "134fa794af682dfa3657c07a85283e24ff2ea114a662f37b8923889fefce05f9"

      def install
        bin.install "opentelemetry1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/prabhatsharma/open-telemetry1/releases/download/v0.1.0/opentelemetry1_0.1.0_Linux_x86_64.tar.gz"
      sha256 "196f2bcd98d4f993ff4bee47045a11b560e054a1678c04bfb323ee8c150ee695"

      def install
        bin.install "opentelemetry1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prabhatsharma/open-telemetry1/releases/download/v0.1.0/opentelemetry1_0.1.0_Linux_arm64.tar.gz"
      sha256 "a2b8024f3af344683d5a48dc0370f446a0c79b0b47241dbd943b2909dc5eef39"

      def install
        bin.install "opentelemetry1"
      end
    end
  end
end
